### ISSUE TITLE
使用CPU车牌识别耗时比较大，应该如何调整?

### ISSUE THREAD

**Issue by woshiwoyali** [ufownl/alpr_utils#1]
使用命令sudo python test.py /home/zjs/Desktop/车牌测试/ --no_yolo   --beam
其中/home/zjs/Desktop/车牌测试/ 是一个目录，目录中包含了11张图片，有些图片中不含有车牌。
运行结果:
粤BD01940 0.9999888 /home/zjs/Desktop/车牌测试/0004.jpg
鲁H0A025 0.9999391 /home/zjs/Desktop/车牌测试/0006.jpeg
苏A2396V 0.99999833 /home/zjs/Desktop/车牌测试/1.jpg
吉AF16666 0.99992096 /home/zjs/Desktop/车牌测试/0002.jpeg
京HF5427 0.9999349 /home/zjs/Desktop/车牌测试/1.jpeg
湘DD08808 0.9999857 /home/zjs/Desktop/车牌测试/0001.jpeg
鲁鲁HC999 0.9942935 /home/zjs/Desktop/车牌测试/200.jpeg
耗时 9 s
11张图片中识别出了其中的7张图片，使用CPU的情况下需要9秒的时候，这个耗时还能否降低?

**Comment by ufownl** [comment]
可以尝使用规模更小的backbone重新训练，也可以尝试使用尺寸更小的图片。
