### ISSUE TITLE
多种类车牌识别

### ISSUE THREAD

**Issue by Juldeng** [ufownl/alpr_utils#11]
尝试一些车牌发现只对单层的识别有效，想请问一下是训练数据没有考虑双层车牌的情况吗，比如中大型卡车、货车、挂车等很多后排都是双层黄牌，对双层黄牌的识别有没有什么指导建议，望回复，多谢！

**Comment by ufownl** [comment]
实际上[CCPD](https://github.com/detectRecog/CCPD)数据集中只有蓝牌，这个模型之所以能检测/识别绿牌、单层黄牌和普通黑牌是用[fake_chs_lp](https://github.com/ufownl/fake_chs_lp)生成的车牌图像训练实现的。

要做双层黄牌的识别的话，比较麻烦的是相关开源数据集比较少，自己收集图像数据的话可能需要比较大的人力做标注。如果你有相关数据来源，可以再通过[fake_chs_lp](https://github.com/ufownl/fake_chs_lp)类似的方式做数据扩增来训练模型。然后就是双层牌照的宽高比跟单层牌照的差别较大，OCR部分可能需要不同的输入图片尺寸来达到更好的识别效果。

**Comment by Juldeng** [comment]
多谢你的回复，只要有双排的数据就可以使用这个attention的img2seq进行ocr识别吗，和单排的单一序列相比，双层的不应该考虑双序列吗

**Comment by ufownl** [comment]
不需要两个序列，双层相对于单层来说，只是序列中的每一位在输入图像上的关注区域不同，还有就是字体不一样，模型应该是可以通过数据学习到这些东西的。

**Comment by ufownl** [comment]
另外有个可能需要调整的地方是做车牌检测的WPOD模型，这个模型目前输出的区域分类只有车牌和非车牌两种，可以考虑改成非车牌、单层车牌、双层车牌三种，方便不同类型车牌输出不同尺寸的图像。

**Comment by Juldeng** [comment]
嗯嗯是的，检测部分要多分一类，多谢指导
