### ISSUE TITLE
训练数据

### ISSUE THREAD

**Issue by zhongwenkun886** [ufownl/alpr_utils#12]
请问这里的车牌检测和车牌识别，分别用什么数据集来训练的？谢谢！

**Comment by ufownl** [comment]
数据集目前只使用了[CCPD](https://github.com/detectRecog/CCPD)。车牌检测部分用[fake_chs_lp](https://github.com/ufownl/fake_chs_lp)生成的车牌图片做了数据扩增；车牌识别部分先用[fake_chs_lp](https://github.com/ufownl/fake_chs_lp)生成的车牌图像做预训练，然后截取[CCPD](https://github.com/detectRecog/CCPD)的车牌图像做微调。

**Comment by zhongwenkun886** [comment]
谢谢，测试一些车牌数据，车牌检测挺好，但识别效果一般，还有很大的优化空间

**Comment by ufownl** [comment]
测试识别有问题的一般是什么情况呢？能否提供一下测试图片？

**Comment by zhongwenkun886** [comment]
![n6](https://user-images.githubusercontent.com/42397285/81394494-94ec0e80-9154-11ea-9961-6ecb9c482f1c.jpg)
![n13](https://user-images.githubusercontent.com/42397285/81394498-961d3b80-9154-11ea-97ab-76b7f7f19373.jpg)
![i36](https://user-images.githubusercontent.com/42397285/81394938-5b67d300-9155-11ea-93c8-efe71d957b0a.jpg)

其实对于清晰的蓝牌识别效果还算不错的，模糊的话效果会差些。绿牌有些会检测不准导致识别错误，双层车牌一般能检测到但识别基本都是错的（识别模型应该是没有训练双层车牌）。

**Comment by ufownl** [comment]
那基本是正常的，CCPD数据集里面只有蓝牌，也完全没做双层车牌，绿牌都完全是通过生成的图像训练的所以效果也会相对差一些。另外训练数据基本都是包含整个车辆的，测试脚本流程也是先检测车辆，然后跑车牌检测，所以车牌占比比较大的图片检测准确率确实不怎么好。

**Comment by zhongwenkun886** [comment]
哦。看来这个wpod-net 泛化能力还是挺不错的，虽然只用单层蓝牌训练，但对双层黄牌还能有这么好的检测效果。

**Comment by ufownl** [comment]
wpod的训练用生成的车牌做了数据扩增的，其中有包含单层的黄牌图像。

**Comment by zhongwenkun886** [comment]
非常感谢指导
