### ISSUE TITLE
车牌检测的wpod网络可以改成并行输入吗 

### ISSUE THREAD

**Issue by zk2ly** [ufownl/alpr_utils#14]
一个图片里面可能有多个车  检测出来后 可以把一个图片里所有车作为一个批量 到wpod网络里进行预测吗

**Comment by ufownl** [comment]
可以，只是批量算出 probability 和 affine 系数之后还是要一个一个重建车牌图像。

**Comment by zk2ly** [comment]
> 可以，只是批量算出 probability 和 affine 系数之后还是�要一个一个重建车牌图像。

感谢
