### ISSUE TITLE
请教如何生成训练数据

### ISSUE THREAD

**Issue by zhongwenkun886** [ufownl/alpr_utils#19]
您好，之前您说过车牌检测部分用fake_chs_lp生成的车牌图片做了数据扩增，车牌识别部分先用fake_chs_lp生成的车牌图像做预训练。我看了下fake_chs_lp，它是生成标准的车牌图像，能否简单描述下如何用它来做数据扩增得到车牌检测和车牌识别的训练数据呢？非常感谢！

**Comment by ufownl** [comment]
是做的on-the-fly的数据扩增，WpodSampler和OcrSampler里面调用的augment_sample就是在干这事儿。

**Comment by zhongwenkun886** [comment]
好的，我研究下代码，非常感谢指导。
