### ISSUE TITLE
您好，发现这个算法写的真的太好了，不知是否方便把怎么训练模型的过程为我们介绍学习一下下

### ISSUE THREAD

**Issue by EllisHui** [ufownl/alpr_utils#20]
您好，发现这个算法写的真的太好了，不知是否方便把怎么训练模型的过程为我们介绍学习一下下

**Comment by ufownl** [comment]
wpod_trainer.py 是训练车牌检测和矫正网络的，如果需要用生成的车牌图像做数据扩增，fake那个参数就设置一个0～1之间的值，用来控制生成图像出现的概率，其他的可以用默认参数跑。

ocr_trainer.py 是用生成图像预训练OCR网络，默认参数就可以训练，不过最好自己写个脚本来跑一下在真实数据上的准确率，如果真实数据准确率不再提高或者开始下降就停止训练防止过拟合生成的图像。

最后用 ocr_finetune.py 加载之前预训练的OCR网络的参数在真实数据上做微调，这个也需要控制一下训练的度，否则容易过拟合蓝牌。
