### ISSUE TITLE
no file: fake/chinese/random_plate

### ISSUE THREAD

**Issue by wudrans** [ufownl/alpr_utils#21]
您好，在运行test.py时报错，发现主要是缺少文件 fake/chinese/random_plate

  from .chinese import random_plate
ImportError: cannot import name 'random_plate'

请问能提供这个文件吗？谢谢

**Comment by ufownl** [comment]
@wudrans clone的时候加上`--recursive`参数

```bash
git clone --recursive https://github.com/ufownl/alpr_utils.git
```

**Comment by Ergou-Liu** [comment]
需要clone第三方依赖库
