### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by rscgg37248** [ufownl/alpr_utils#23]
Hi,when I run server.py:

File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied

Any idea on how to resolve this problem?thanks

**Comment by ufownl** [comment]
Hi @rscgg37248 , the default port number of server.py is 80, it requires root permission. So you could try to run it via `sudo`, or change the port number via `--port` parameter.
