### ISSUE TITLE
请问finetune.json文件怎么生成呢？

### ISSUE THREAD

**Issue by Eliza-wxq** [ufownl/alpr_utils#24]

**Comment by ufownl** [comment]
finetune.json 格式跟 dataset.json 的格式完全相同，可以按 dataset.json 相同的方式通过 CCPD 数据集来生成。不过因为 CCPD 数据集中车牌大多集中在一个省份，数据样本分布跟实际偏差可能会比较大，可以筛选一下保证不同省份的车牌都有差不多的数量。
